import "./globals.css";
import Wrapper from "./wrapper";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Audiophile",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider frontendApi={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <Wrapper children={children} />
    </ClerkProvider>
  );
}
