"use client";

import "./globals.css";
import { MyProvider } from "../context/MyContext";
import Nav from "../components/nav/Nav";
import Footer from "../components/footer/Footer";
import Search from "../components/search/Search";
import ScrollToTop from "../components/ScrollToTop";

import { ClerkProvider } from "@clerk/nextjs";
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function Wrapper({ children }) {
  return (
    <ClerkProvider frontendApi={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en">
        <MyProvider>
          <body>
            <ScrollToTop />
            <Nav />
            <Search />
            {/* <div className="searchBar">
              <div className="forBottom">
                <img src={search.src} alt="search" onClick={() => find()} />
                <input
                  type="text"
                  placeholder="Search for products"
                  className="searchInput"
                  ref={inputw}
                />
              </div> 
  </div>*/}

            {children}
            <Footer />
          </body>
        </MyProvider>
      </html>
    </ClerkProvider>
  );
}
